#!/bin/bash
#Bash scripting

# Installing Kraken2
conda install -c bioconda kraken2
kraken2 --version
version 2.17.1           
Build pl5321h077b44d_0
Copyright 2013-2023, Derrick Wood (dwood@cs.jhu.edu)

#Installing a database
mkdir kraken2_db && cd kraken2_db
mkdir standard_8 && cd standard_8

# downloading the Standard-8 (8 GB) database, last updated febuary 2026
wget https://genome-idx.s3.amazonaws.com/kraken/k2_standard_08_GB_20260226.tar.gz

#Extracting 
tar -xzvf k2_standard_08_GB_20260226.tar.gz 

#Checking contents
ls ~/kraken2_db/standard/
should see
hash.k2d -> The k-mer hash table (the big one, ~8 GB)
opts.k2d  -> Database build options
taxo.k2d -> Taxonomy information

#Randomly selecting 3 high NRCD patients from the 39 used in the study
awk -F'\t' '$3 == "high-NRCD" {print $1"\t"$2"\t"$3}' metadata_table.tsv > high_nrcd_all.txt
shuf -n 5 high_nrcd_all.txt > high_nrcd_selected.txt

cat high_nrcd_selected.txt
ERR12025082	1807	high-NRCD
ERR12025102	1837	high-NRCD
ERR12025074	1797	high-NRCD

#Randomly selecting 3 out of the 49 control samples used in the study
shuf -n 5 tCD_controls_metadata.tsv > tCD_selected.txt

cat tCD_selected.txt
SRR22402259	Cii071	tCD_control
SRR22402265	Cii045	tCD_control
SRR22402328	CMa003	tCD_control

echo "    High-NRCD selected    " > selection_log.txt
cat high_nrcd_selected.txt >> selection_log.txt
echo "    tCD controls selected    " >> selection_log.txt
cat tcd_selected.txt >> selection_log.txt

cat selection_log.txt
   High-NRCD selected    
ERR12025082	1807	high-NRCD
ERR12025102	1837	high-NRCD
ERR12025074	1797	high-NRCD

    tCD controls selected     
SRR22402259	Cii071	tCD_control
SRR22402265	Cii045	tCD_control
SRR22402328	CMa003	tCD_control


#Downloading the seleted high-NRCD samples from ENA
for run in ERR12025082 ERR12025102 ERR12025074 ERR12025109 ERR12025104; do
    echo "Getting URLs for $run..."
    urls=$(wget -qO- "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=${run}&result=read_run&fields=fastq_ftp&format=tsv" \
           | tail -1 | cut -f2 | tr ';' '\n')
    
    # Download each file
    for url in $urls; do
        wget -c -P ~assignment_03/metagenomics/high_nrcd "ftp://${url}"
    done
    echo "Done $run"
done

#Downloading the tCD controls from the ENA database browser
for run in SRR22402259 SRR22402265 SRR22402328 SRR22402331 SRR22402374; do
    echo "$(date): Downloading $run..."
    urls=$(wget -qO- "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=${run}&result=read_run&fields=fastq_ftp&format=tsv" \
           | tail -1 | cut -f2 | tr ';' '\n')
    
    for url in $urls; do
        wget -c "ftp://${url}"
    done
    echo "$(date): Done $run"
done


#Quality Control
fastqc ~/binf_6110/assignment_03/metagenomics/high_nrcd/*.fastq.gz \
       ~/binf_6110/assignment_03/metagenomics/tcd/*.fastq.gz \
       --outdir ~/binf_6110/assignment_03/metagenomics/qc/raw \
       --threads 4

conda install -c bioconda multiqc -y

multiqc ~/binf_6110/assignment_03/metagenomics/qc/raw \
        --outdir ~/binf_6110/assignment_03/metagenomics/qc/raw

#Kraken2
mkdir -p ~/binf_6110/assignment_03/metagenomics/kraken2/high_nrcd
mkdir -p ~/binf_6110/assignment_03/metagenomics/kraken2/tcd
~~~
#Test runs showed when working with confidence 0.15 for sample 1 in the high_nrcd group, that majority of the sequences were left unclassified. So I tested whether dropping the confidence to O.O5 and 0 improved this. Below are the results 
#Confidence 0.15
304973 sequences classified (1.74%)
17192235 sequences unclassified (98.26%)

#Confidence 0.05
8674762 sequences classified (49.58%)
  8822446 sequences unclassified (50.42%)

#Confidence 0
 12491139 sequences classified (71.39%)
  5006069 sequences unclassified (28.61%)
#Moving forward, the confidence level will be set to the default

# Running Kraken and Bracken through Digial Alliance cluster Nibi

nano /scratch/mogakwu/assignment_03/kraken2_job.sh
#!/bin/bash
#SBATCH --account=def-cottenie
#SBATCH --job-name=kraken2_nrcd
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --output=%x-%j.out
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=mogakwu@uoguelph.ca

module load StdEnv/2023
module load kraken2/2.1.3
module load bracken/3.0

DB=/scratch/mogakwu/kraken2_db/standard_8
READS=/scratch/mogakwu/assignment_03/metagenomics
OUT=/scratch/mogakwu/assignment_03/kraken2_output

mkdir -p $OUT/high_nrcd $OUT/tcd

for run in ERR12025082 ERR12025102 ERR12025074 \
           SRR22402259 SRR22402265 SRR22402328; do
    echo "$(date): Running Kraken2 on $run..."
    if [[ $run == ERR* ]]; then
        OUTDIR=$OUT/high_nrcd
        INDIR=$READS/high_nrcd
    else
        OUTDIR=$OUT/tcd
        INDIR=$READS/tcd
    fi
    kraken2 --db $DB \
            --paired \
            --gzip-compressed \
            --threads 16 \
            --output ${OUTDIR}/${run}.kraken \
            --report ${OUTDIR}/${run}.report \
            ${INDIR}/${run}_1.fastq.gz \
            ${INDIR}/${run}_2.fastq.gz
    echo "$(date): Done $run"
done

#Bracken abundane reestimation
for run in ERR12025082 ERR12025102 ERR12025074; do
    bracken -d $DB \
            -i $OUT/high_nrcd/${run}.report \
            -o $OUT/high_nrcd/${run}.bracken \
            -r 150 -l S -t 10
done

for run in SRR22402259 SRR22402265 SRR22402328; do
    bracken -d $DB \
            -i $OUT/tcd/${run}.report \
            -o $OUT/tcd/${run}.bracken \
            -r 150 -l S -t 10
done

echo "$(date): All done!"
sbatch kraken2_job.sh

#Conversion to BIOM on DRAC Nibi cluster
kraken-biom stool_sample_bracken_species.report
#Loading python module with numpy and pandas included
module load python/3.11

#Creating and activating python virtual environment
python -m venv ~/kraken_biom_env
source ~/kraken_biom_env/bin/activate

#Installing dependencies in virtual environment
pip install numpy pandas

#Installing Kraken-biom
pip install kraken-biom
kraken-biom --version

ls /scratch/mogakwu/assignment_03/kraken2_output_2/high_nrcd
ERR12025074.bracken                 ERR12025082.report
ERR12025074.kraken                  ERR12025082_bracken_species.report
ERR12025074.report                  ERR12025102.bracken
ERR12025074_bracken_species.report  ERR12025102.kraken
ERR12025082.bracken                 ERR12025102.report
ERR12025082.kraken                  ERR12025102_bracken_species.report
(kraken_biom_env) [mogakwu@l5.nibi assignment_03]$ ls /scratch/mogakwu/assignment_03/kraken2_output_2/tcd
SRR22402259.bracken                 SRR22402265.report
SRR22402259.kraken                  SRR22402265_bracken_species.report
SRR22402259.report                  SRR22402328.bracken
SRR22402259_bracken_species.report  SRR22402328.kraken
SRR22402265.bracken                 SRR22402328.report
SRR22402265.kraken                  SRR22402328_bracken_species.report

#Combining all the bracken_species.report files into one BIOM file 
cd /scratch/mogakwu/assignment_03/kraken2_output_2

kraken-biom \
  high_nrcd/ERR12025082_bracken_species.report \
  high_nrcd/ERR12025102_bracken_species.report \
  high_nrcd/ERR12025074_bracken_species.report \
  tcd/SRR22402259_bracken_species.report \
  tcd/SRR22402265_bracken_species.report \
  tcd/SRR22402328_bracken_species.report \
   

kraken-biom \
  high_nrcd/ERR12025082.report \
  high_nrcd/ERR12025102.report \
  high_nrcd/ERR12025074.report \
  tcd/SRR22402259.report \
  tcd/SRR22402265.report \
  tcd/SRR22402328.report \
  --min S \
  --fmt json \
  -o combined4.biom 
